### PR TITLE
chore: update cairo-lang to ^0.5.0

### PR DESCRIPTION
**Pull request by gakonst**
As title, dep bump.

### CODE REVIEW

**Comment by FabijanC** [comment]
Thank you for taking interest in the project. I'm currently working on a new version that will both update the dependencies and adapt to the alpha 3 testnet. I was hoping to release it tomorrow.

**Comment by FabijanC** [comment]
Seems that just updating the deps is not sufficient, run the devnet and try running
```
starknet deploy --contract PATH --gateway_url http://localhost:5000
```
It should fail with 500 Internal Server Error because 0.5.0 introduced breaking changes.


What do you say I close this this PR?

**Comment by gakonst** [comment]
Ah OK sounds good to me. Looking forward to the update.

**Comment by FabijanC** [comment]
The changes proposed by this PR are included in #5 and the new version (v0.1.3). Check it out:
https://github.com/Shard-Labs/starknet-devnet/releases/tag/v0.1.3

**Pull request closed without merging**
